sudo: required
env:
  matrix:
    - PLATFORM=centos DISTRO=el OS_VERSION=6 DOCKER_IMAGE=centos:centos6
    - PLATFORM=centos DISTRO=el OS_VERSION=7 DOCKER_IMAGE=centos:centos7
    - PLATFORM=debian DISTRO=debian OS_VERSION=stretch DOCKER_IMAGE=debian:stretch
    - PLATFORM=debian DISTRO=debian OS_VERSION=jessie DOCKER_IMAGE=debian:jessie
    - PLATFORM=ubuntu DISTRO=ubuntu OS_VERSION=trusty DOCKER_IMAGE=ubuntu:trusty
    - PLATFORM=ubuntu DISTRO=ubuntu OS_VERSION=xenial DOCKER_IMAGE=ubuntu:xenial

services:
  - docker

script:
  - make package-${PLATFORM}

before_deploy: "ls -la"

deploy:
  provider: packagecloud
  repository: main
  username: twindb
  token:
    secure: "THfnc8jCVfSdcBM11WXbnDozqnn8HhgSGOqXit0u13nHvlW2C+8oBMyR0dEWVarZBISU+2rBrq2ESrNyWypNcPaA7W3sGObhbjjG2u8/F0I/lbKpQLs5sKVvo2gQadkGmgY2JDPVrp9yBABNpczz6d8fsFblJ56LjY2nPi7j43vLhtQoTdqxOj81fjc6kYCFRYMXLSuvkzcCbxyCen0V86hjE6sda4BlWSxaMAr+SUNXnH2bXD5uJm6YWwMjdpzO/2+mlGyPSB3PEp4qoAwchz5E4P+H1oeOr0WWDVeGcjo3/si3qs3mUKLEdk9/mUpzjzehS0vv9el3lpO/jsWmqZl6JieucMD1jVlZ/2OTB6O5rL50nupFqb0SGO+YgkmS4QgdxjVr+XWf+lnDzGg5al98d+pGNgrU1APmSXNAvMD0pCT6HTtv2SLphEUO2+REwjdA8S+rzs9fGV9I7Jg7IdjZrWRfDYbbCk+knEuoq95aXOS5A0kG1yytA21azLw8hi+qvA3n+bG1DZrQMJjIb5OROX/Ua/OumewqTaaSe9Eoh+AUTrIHJZzo6QMoRLverqITV5GWOzidCXxmitBrKi0+VKzdcjdW+DpcNdA+LTejBjqjDC6+dU1Ealcx3XP3DpznEauRw7tdOg0PgqlGUo8NWmjsalwP8Dm7FWPqPa0="
  dist: ${DISTRO}/${OS_VERSION}
  skip_cleanup: true
  local-dir: build
  on:
      branch: release-0.9.1