sudo: required
env:
  matrix:
    - PLATFORM=centos DISTRO=el OS_VERSION=6 DOCKER_IMAGE=centos:centos6
    - PLATFORM=centos DISTRO=el OS_VERSION=7 DOCKER_IMAGE=centos:centos7
    - PLATFORM=debian DISTRO=debian OS_VERSION=stretch DOCKER_IMAGE=debian:stretch
    - PLATFORM=debian DISTRO=debian OS_VERSION=jessie DOCKER_IMAGE=debian:jessie
    - PLATFORM=ubuntu DISTRO=ubuntu OS_VERSION=trusty DOCKER_IMAGE=ubuntu:trusty
    - PLATFORM=ubuntu DISTRO=ubuntu OS_VERSION=xenial DOCKER_IMAGE=ubuntu:xenial

services:
  - docker

script:
  - make package-${PLATFORM}